### ISSUE TITLE
Bring back the rentry for v4

### ISSUE THREAD

**Issue by jijirae** [jijirae/thesecondopinion#6]
sjhkdgf;skajdfskj i'll do it later

**Comment by FestiveByteRider** [comment]
I was bored so I started but you did some cool stuff I can't be bothered figuring out how to do so here's the in progress one to save you some time and I dmed you the edit code
https://rentry.co/thesecondopinionfsb

**Comment by jijirae** [comment]
Copied and moved to original link. Thank you, Festive!
https://rentry.co/thesecondopinion
